apiVersion: v1
kind: Namespace
metadata:
  name: azsk-scanner

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azsk-scanner-clusterrole
  namespace: azsk-scanner
rules:
- apiGroups: ["*"]
  resources: ["pods","deployments","nodes","serviceaccounts","configmaps","clusterrolebindings"]
  verbs: ["get", "watch", "list"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: azsk-scanner-account
  namespace: azsk-scanner

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azsk-scanner-rolebinding
  namespace: azsk-scanner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azsk-scanner-clusterrole
subjects:
- kind: ServiceAccount
  name: azsk-scanner-account
  namespace: azsk-scanner
